### ISSUE TITLE
about visualization codes

### ISSUE THREAD

**Issue by Roywangj** [junshengzhou/3D-OAE#3]
Hi @junshengzhou , thanks for your great work. The visualization results in paper is very beautiful(Fig.2,4,7), will you be kind enough to release the code of visualization? Besides, i find the objects in the figure don't have shadows, how do you achieve that, if you use mitsuba?

**Comment by junshengzhou** [comment]
Hi,

Really sorry for the late reply... Of course, I am happy to share the visualization approach with you.

We visualize the figures in Fig.2,4,7 with [Keyshot](https://www.keyshot.com/), and turn off the shadows for a clear visualization.
You can refer to the script from [this repo](https://github.com/AllenXiangX/SnowflakeNet/blob/main/visualization/vis_splitting.py) with `def create_pcd_mesh()` in Line.65 for generating a sphere mesh for each point of the point cloud and save is as an '.obj' file. Then put it in the Keyshot for rendering.

Please feel free to contact me if you have further questions on visualization or if I am not clear enough, and thanks for your kind words on our figures!

Best, 
Junsheng

**Comment by Roywangj** [comment]
Hi, 
Thanks for your reply, it helps a lot.
